FROM node:19.4-bullseye AS build

WORKDIR /usr/src/app

COPY package*.json ./

RUN --mount=type=cache,target=/usr/src/app/.npm \
  npm set cahce usr/src/app/.npm && \
  npm install

COPY . .

CMD ["npm", "run", "dev"]
